# A_1: Array Creation

In [17]:
# Introduction:

# There are 6 general mechanisms for creating arrays:

# 1. Conversion from other Python structures (i.e. lists and tuples)
# 2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
# 3. Replicating, joining, or mutating existing arrays
# 4. Reading arrays from disk, either from standard or custom formats
# 5. Creating arrays from raw bytes through the use of strings or buffers
# 6. Use of special library functions (e.g., random)

# You can use these methods to create ndarrays or Structured arrays. """

In [18]:
# Converting Python sequences to NumPy arrays

# NumPy arrays can be defined using Python sequences such as lists and tuples. 

# 1. a list of numbers will create a 1D array,
# 2. a list of lists will create a 2D array,
# 3. further nested lists will create higher-dimensional arrays. 

# In general, any array object is called an ndarray in NumPy.

In [19]:
# load the library

import numpy as np

In [20]:
# creation of types of arrays

a_one_dim = np.array([[1, 2, 3]])
a_two_dim = np.array([[1, 2, 3], [4, 5, 6]])
a_three_dim = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

In [21]:
# prints one dimensional array

print(a_one_dim)   

[[1 2 3]]


In [22]:
# prints two dimensional array

print(a_two_dim)

[[1 2 3]
 [4 5 6]]


In [23]:
# prints multi-dimensional array

print(a_three_dim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
# numpy.array defines a new array and also considers the dtype of the elements in the array, which can be specified explicitly. 
# Error occurs when values do not fit the dtype.

np.array([127, 128, 129], dtype=np.int8)

array([ 127, -128, -127], dtype=int8)

In [25]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


In [26]:
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

signed c: [-3 -3 -3] int64


In [27]:
# Operations with two arrays of the same dtype uint32, results in same type. 
# Operations with different dtype, assigns a new type.
# uint32 and int32 can both be represented in as int64.